# -*- coding: utf-8 -*-
"""houseprice-.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AfeMQjdgch4034i4WIG0fxeMPE5-PLPG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv("Real_estate.csv")

print("\nSummary statistics:")
print("\nFirst 5 rows:")
print(df.head())

print("\nDataset info:")
df.info()

print(df.describe())

print("\nMissing values:")
print(df.isnull().sum())

df = df.dropna()
print(df.isnull().sum())

plt.figure(figsize=(10, 8))
correlation_matrix = df.drop(columns=['ID']).corr()
sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    linewidths=0.5)
plt.title("Correlation heatmap of features")
plt.show()

num_cols = df.drop(columns=['ID']).columns
plt.figure(figsize=(14, 6))
df[num_cols].boxplot()
plt.title("Box Plot of numerical features")
plt.tight_layout()
plt.show()

x=df.drop('Price',axis=1)
y=df['Price']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

print("MODEL PERFORMANCE")
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("R² Score:", r2)

print("\nMODEL PERFORMANCE  VISUALIZATION")
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, alpha=0.5)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red')
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted")
plt.show()

results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

results.to_csv("predictions.csv", index=False)
print("Saved predictions to predictions.csv")

